---
language: python
python: "2.7"

install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script: ansible-playbook tests/site.yml -i tests/inventory --syntax-check
