---

- name: ssh check sshd config and restart
  command: '{{ ssh_daemon_bin }} -t'
  notify:
    - 'ssh restart daemon'

- name: ssh restart daemon
  service:
    name: '{{ ssh_service }}'
    state: restarted
